name: Publish Quarto Dashboard

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.6.0
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          uv pip install jupyter nbformat pandas matplotlib plotly

      - name: Render Quarto Project
        # Eliminamos working-directory si tu archivo _quarto.yml está en la raíz
        # Si está dentro de /dashboard, asegúrate que el output-dir en el yaml sea ../docs
        run: |
          uv run quarto render dashboard --output-dir docs

      - name: Prevent Jekyll
        run: touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          keep_files: false
